services:
  ansible:
    container_name: ansible
    image: ghcr.io/ansible-community/community-ee-base:latest
    volumes:
      - ./controlnode:/runner/:ro
    environment:
      - ANSIBLE_CONFIG=/runner/ansible.cfg
