- name: Download Webmin GPG key
  ansible.builtin.get_url:
    url: https://webmin.com/jcameron-key.asc
    dest: /usr/share/keyrings/webmin.asc
    mode: '0644'
- name: Add Webmin repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/webmin.asc] http://download.webmin.com/download/repository sarge contrib
    filename: webmin
    state: present
