- name: Configure UFW Firewall
  hosts: node
  become: true
  gather_facts: false
  vars:
    alllowed_ports:
      - 22
      - 80
      - 10000
  tasks:
    - name: Set logging
      community.general.ufw:
        logging: 'on'
    - name: Deny everything and enable UFW
      community.general.ufw:
        state: enabled
        policy: deny
    - name: Allow ports
      community.general.ufw:
        rule: allow
        to_port: "{{ allowed_port }}"
      notify: Restart ufw service
      loop: "{{ alllowed_ports }}"
      loop_control:
        loop_var: allowed_port
