- name: Install nginx
  hosts: nginx
  tasks:
    - name: Install nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        state: present
      notify: start nginx
    - name: Install the firewall package
      become: true
      ansible.builtin.apt:
        name: ufw
        state: present
    - name: Start ufw service
      become: true
      ansible.builtin.service:
        name: ufw
        state: started
        enabled: true
    - name: Deny everything and enable UFW
      become: true
      community.general.ufw:
        state: enabled
        policy: deny
    - name: Allow SSH
      become: true
      community.general.ufw:
        rule: allow
        to_port: ssh
    - name: Set logging
      become: true
      community.general.ufw:
        logging: 'on'
  handlers:
    - name: Start nginx service
      become: true
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
      listen: start nginx
    - name: Allow HTTP
      become: true
      community.general.ufw:
        rule: allow
        to_port: http
      listen: start nginx
